server:
  port: 8080

spring:
    datasource:
        name: luckyhit_api
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          filters: stat
          driver-class-name: org.postgresql.Driver
          url: jdbc:postgresql://localhost:5432/LuckyHit?characterEncoding=utf8
          username: postgres
          password: 123456
          initial-size: 1
          min-idle: 1
          max-active: 20
          max-wait: 60000
          time-between-eviction-runs-millis: 60000
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.luckyhit.entity

#pagehelper
pagehelper:
    helperDialect: postgresql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check